# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Why Hello There!
  Just a reminder that I am not a developer, just a tweaker and explorer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://wardsparadox.github.io" # the base hostname & protocol for your site
github_username:  WardsParadox

# Build settings
markdown: kramdown
